### ISSUE TITLE
TerraformCDK integration

### ISSUE THREAD

**Issue by bryan-bar** [EnterpriseDB/edb-terraform#29]
**Problem:**
We currently use Python and jinja templates to help us overcome some of the limitations of HCL. This requires the passing of variables between python, jinja and then hcl which reduces reusability. It also requires us needing to go back and forth between languages at times while losing support from our IDE when templating and needing to manually test changes. This leads into the need to duplicate variables, use mixed syntax loops(jinja and hcl), and one-time conversions when using nested loops/mappings due to the `for_each` and `count` in HCL and more.

https://github.com/EnterpriseDB/edb-terraform/blob/main/edbterraform/data/templates/aws/main.tf.j2#L43-L64
https://github.com/EnterpriseDB/edb-terraform/blob/main/edbterraform/data/templates/aws/main.tf.j2#L113-L120
https://github.com/EnterpriseDB/edb-terraform/blob/main/edbterraform/data/templates/aws/main.tf.j2#L65-L76

**Possible Solution:**
On August 2022, terraform released its CDK under `generally available` starting with `v0.12` and Typescript/Python support. 
This could remove our need for jinja templating and allow for the use of python directly with minimal HCL modules. 
* It provides `cdktf convert`, which can convert terraform modules for use within python to help create `Constructs` which are called inside of a `Stack`(provider context). 
* Modules can also be left as is while leveraging the conversion tool to provide module testing with pytest and allowing us to import the modules in python.
* Once files are generated with the cdk tool, or library, users can use regular terraform commands and reference it within other HCL files.

**Comment:**
Pulumi is much more powerful but it has not been widely adopted yet and it would require reworking some workflows. I am not sure of using 3rd party tools such as terragrunt now that Terraform is developing its own tooling, however, this CDK may have breaking changes and typescript might be better supported as it is based on aws's cdk.

Terraform CDK Links:
[Architecture](https://developer.hashicorp.com/terraform/cdktf/concepts/cdktf-architecture)
[Modules](https://developer.hashicorp.com/terraform/cdktf/concepts/modules)
[Unit-Tests](https://developer.hashicorp.com/terraform/cdktf/test/unit-tests)
[Python API](https://developer.hashicorp.com/terraform/cdktf/api-reference/python)

**Comment by shaktishikha** [comment]
We are not going to work on this issue because we are no longer going to use Terraform CDK and we will be looking for alternate solutions.
